kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-test-bind
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-test
subjects:
- kind: Group
  namespace: web
  name: 6b9fd38e-863b-48b3-b557-902d8e882750