kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-edit-api
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit-access-role
subjects:
- kind: Group
  namespace: api
  name: 85b19b67-835a-4628-81ca-52386ce12849

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-access-web
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-access-role
subjects:
- kind: Group
  namespace: web
  name: 85b19b67-835a-4628-81ca-52386ce12849