# poi.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  selector: 
    matchLabels: 
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: registryhrh2972.azurecr.io/tripinsights/poi:1.0
          name: poi
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/secrets"
            readOnly: true                        
          env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sqluser
                key: sqluser
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlpassword
                key: sqlpassword      
          - name: SQL_SERVER
            value: sqlserverhrh2972.database.windows.net
          - name: SQL_DBNAME
            value: mydrivingDB
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"                                            