apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: api
spec:
  selector:
    app: user-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP