# userprofile.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  selector: 
    matchLabels: 
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
        namespace: api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: registryhrh2972.azurecr.io/tripinsights/userprofile:1.0
          name: userprofile
          ports:
            - containerPort: 80
              name: http
          env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql
                key: sqluser
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql
                key: sqlpassword
          - name: SQL_SERVER
            value: sqlserverhrh2972.database.windows.net
          - name: SQL_DBNAME
            value: mydrivingDB                              