# user-java.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  selector: 
    matchLabels: 
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: registryhrh2972.azurecr.io/tripinsights/user-java:1.0
          name: user-java
          ports:
            - containerPort: 80
              name: http
          env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql
                key: sqluser
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql
                key: sqlpassword
          - name: SQL_SERVER
            value: sqlserverhrh2972.database.windows.net
          - name: SQL_DBNAME
            value: mydrivingDB                              